apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm-optimizer-dev
labels:
  - pairs:
      app.kubernetes.io/name: vllm-optimizer-dev
      app.kubernetes.io/component: development
      app.kubernetes.io/version: "dev"
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
    patch: |- 
      - op: replace
        path: /metadata/name
        value: vllm-optimizer-dev
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: vllm-optimizer-monitoring-view
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: vllm-optimizer-dev
  - target:
      kind: Deployment
      name: vllm-optimizer-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/joopark/vllm-optimizer-backend:dev
  - target:
      kind: Deployment
      name: vllm-optimizer-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/joopark/vllm-optimizer-frontend:dev
      - op: replace
        path: /metadata/annotations/image.openshift.io~1triggers
        value: '[{"from":{"kind":"ImageStreamTag","name":"vllm-optimizer-frontend:latest","namespace":"vllm-optimizer-dev"},"fieldPath":"spec.template.spec.containers[0].image","pause":"false"}]'
  - target:
      kind: ConfigMap
      name: vllm-optimizer-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: "development"
      - op: add
        path: /data/VLLM_NAMESPACE
        value: "vllm-lab-dev"
      - op: add
        path: /data/VLLM_DEPLOYMENT_NAME
        value: "llm-ov"
      - op: add
        path: /data/VLLM_CR_TYPE
        value: "inferenceservice"
      - op: add
        path: /data/VLLM_ENDPOINT
        value: "http://llm-ov-predictor.vllm-lab-dev.svc.cluster.local:8080"
  - target:
      kind: PrometheusRule
      name: vllm-optimizer-alerts
    patch: |-
      - op: replace
        path: /spec/groups/2/rules/0/expr
        value: |
          kube_deployment_status_replicas_available{deployment="llm-ov-predictor"}
          <
          kube_deployment_spec_replicas{deployment="llm-ov-predictor"} * 0.5
