apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm-optimizer-dev
labels:
  - pairs:
      app.kubernetes.io/name: vllm-optimizer-dev
      app.kubernetes.io/component: development
      app.kubernetes.io/version: "dev"
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
    patch: |- 
      - op: replace
        path: /metadata/name
        value: vllm-optimizer-dev
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: vllm-optimizer-monitoring-view
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: vllm-optimizer-dev
  - target:
      kind: Deployment
      name: vllm-optimizer-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/joopark/vllm-optimizer-backend:dev
  - target:
      kind: Deployment
      name: vllm-optimizer-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/joopark/vllm-optimizer-frontend:dev
  - target:
      kind: ConfigMap
      name: vllm-optimizer-config
    patch: |-
      - op: add
        path: /data/ALLOWED_ORIGINS
        value: "https://vllm-optimizer-dev.apps.compact.jooan.local"
      - op: add
        path: /data/VLLM_ENDPOINT
        value: "http://openshift-ai-inference-openshift-default.openshift-ingress.svc/llm-d-demo/small-llm-d"
