apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm-lab-dev
resources:
  - ../base
patches:
  - target:
      kind: NetworkPolicy
      name: vllm-networkpolicy
    patch: |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: vllm-networkpolicy
        namespace: vllm-lab-dev
      spec:
        ingress:
        - from:
          - podSelector: {}
          - namespaceSelector:
              matchLabels:
                network.openshift.io/policy-group: ingress
          - namespaceSelector:
              matchLabels:
                network.openshift.io/policy-group: monitoring
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: openshift-kube-apiserver
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: vllm-optimizer-dev
            podSelector:
              matchLabels:
                app: vllm-optimizer-backend
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: openshift-lightspeed
  - target:
      kind: InferenceService
      name: llm-ov
    patch: |
      apiVersion: serving.kserve.io/v1beta1
      kind: InferenceService
      metadata:
        name: llm-ov
      spec:
        predictor:
          model:
            args:
              - --served-model-name=OpenVINO/Qwen3.5-2B-int4-ov
              - --max-num-seqs=32
              - --gpu-memory-utilization=0.90
              - --max-model-len=8192
              - '--override-generation-config={"temperature":0}'
              - --enable-prefix-caching
