"""
Prometheus metrics definitions for vLLM Optimizer backend.
Exposes metrics in Prometheus format for OpenShift Monitoring.
"""

from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    REGISTRY,
    generate_latest,
    CONTENT_TYPE_LATEST
)

# ── Metric Definitions ───────────────────────────────────────────────────────

# Counters (cumulative)
vllm_request_success_total = Counter(
    'vllm_request_success_total',
    'Total number of successful vLLM requests',
    ['model']
)

vllm_generation_tokens_total = Counter(
    'vllm_generation_tokens_total',
    'Total number of tokens generated by vLLM',
    ['model']
)

# Gauges (point-in-time)
vllm_num_requests_running = Gauge(
    'vllm_num_requests_running',
    'Number of currently running vLLM requests'
)

vllm_num_requests_waiting = Gauge(
    'vllm_num_requests_waiting',
    'Number of requests waiting in queue'
)

vllm_gpu_cache_usage_perc = Gauge(
    'vllm_gpu_cache_usage_perc',
    'GPU KV cache usage percentage'
)

vllm_gpu_utilization = Gauge(
    'vllm_gpu_utilization',
    'GPU utilization percentage'
)

vllm_time_to_first_token_seconds = Histogram(
    'vllm_time_to_first_token_seconds',
    'Time to first token distribution',
    ['model']
)

vllm_e2e_request_latency_seconds = Histogram(
    'vllm_e2e_request_latency_seconds',
    'End-to-end request latency distribution',
    ['model']
)


# ── API Surface ─────────────────────────────────────────────────────────────

def update_metrics(data):
    """
    Update Prometheus metrics with latest VLLMMetrics data.
    
    Args:
        data: VLLMMetrics object containing current metrics
    """
    # Gauges - set directly
    vllm_num_requests_running.set(data.running_requests)
    vllm_num_requests_waiting.set(data.waiting_requests)
    vllm_gpu_cache_usage_perc.set(data.kv_cache_usage_pct)
    vllm_gpu_utilization.set(data.gpu_utilization_pct)
    
    # Counters - increment by rate values (simplified approach)
    # In production, these should be cumulative counts from vLLM
    vllm_request_success_total.labels(model='default').inc(data.requests_per_second)
    vllm_generation_tokens_total.labels(model='default').inc(data.tokens_per_second)
    
    # Histograms - observe latency values (convert ms to seconds)
    vllm_time_to_first_token_seconds.labels(model='default').observe(data.mean_ttft_ms / 1000.0)
    vllm_e2e_request_latency_seconds.labels(model='default').observe(data.mean_e2e_latency_ms / 1000.0)


def generate_metrics():
    """
    Generate Prometheus-formatted metrics output.
    
    Returns:
        bytes: Metrics in Prometheus text format
    """
    return generate_latest(REGISTRY)
