import pytest
from fastapi.testclient import TestClient


def test_metrics_endpoint_plaintext():
    """Test /api/metrics endpoint returns correct Prometheus format"""
    import backend.metrics.prometheus_metrics as prom
    
    # Generate realistic Prometheus output for all 8 metrics
    fake_metrics_output = b"""# HELP vllm_request_success_total Total number of successful vLLM requests
# TYPE vllm_request_success_total counter
vllm_request_success_total{model="default"} 150.0

# HELP vllm_generation_tokens_total Total number of tokens generated by vLLM
# TYPE vllm_generation_tokens_total counter
vllm_generation_tokens_total{model="default"} 45230.0

# HELP vllm_num_requests_running Number of currently running vLLM requests
# TYPE vllm_num_requests_running gauge
vllm_num_requests_running 3.0

# HELP vllm_num_requests_waiting Number of requests waiting in queue
# TYPE vllm_num_requests_waiting gauge
vllm_num_requests_waiting 7.0

# HELP vllm_gpu_cache_usage_perc GPU KV cache usage percentage
# TYPE vllm_gpu_cache_usage_perc gauge
vllm_gpu_cache_usage_perc 65.5

# HELP vllm_gpu_utilization GPU utilization percentage
# TYPE vllm_gpu_utilization gauge
vllm_gpu_utilization 78.2

# HELP vllm_time_to_first_token_seconds Time to first token distribution
# TYPE vllm_time_to_first_token_seconds histogram
vllm_time_to_first_token_seconds_seconds_bucket{le="0.1",model="default"} 15.0
vllm_time_to_first_token_seconds_bucket{le="0.5",model="default"} 120.0
vllm_time_to_first_token_seconds_bucket{le="1.0",model="default"} 145.0
vllm_time_to_first_token_seconds_bucket{le="+Inf",model="default"} 150.0
vllm_time_to_first_token_seconds_sum{model="default"} 89.5
vllm_time_to_first_token_seconds_count{model="default"} 150.0

# HELP vllm_e2e_request_latency_seconds End-to-end request latency distribution
# TYPE vllm_e2e_request_latency_seconds histogram
vllm_e2e_request_latency_seconds_bucket{le="0.1",model="default"} 5.0
vllm_e2e_request_latency_seconds_bucket{le="0.5",model="default"} 45.0
vllm_e2e_request_latency_seconds_bucket{le="1.0",model="default"} 95.0
vllm_e2e_request_latency_seconds_bucket{le="+Inf",model="default"} 150.0
vllm_e2e_request_latency_seconds_sum{model="default"} 234.7
vllm_e2e_request_latency_seconds_count{model="default"} 150.0
"""

    def fake_generate_metrics():
        return fake_metrics_output
    
    monkeypatch = pytest.MonkeyPatch()
    monkeypatch.setattr(prom, 'generate_metrics', fake_generate_metrics)

    from backend.main import app
    client = TestClient(app)
    resp = client.get("/api/metrics")
    
    # Test basic response properties
    assert resp.status_code == 200
    assert resp.headers.get("content-type", "").startswith("text/plain")
    
    # Test that all base metric names are present
    text = resp.text
    base_metrics = [
        "vllm_request_success_total",
        "vllm_generation_tokens_total", 
        "vllm_num_requests_running",
        "vllm_num_requests_waiting",
        "vllm_gpu_cache_usage_perc",
        "vllm_gpu_utilization",
        "vllm_time_to_first_token_seconds",
        "vllm_e2e_request_latency_seconds"
    ]
    
    for metric in base_metrics:
        assert metric in text, f"Metric {metric} not found in response"
    
    # Test that HELP and TYPE lines are present for each metric
    for metric in base_metrics:
        help_line = f"# HELP {metric}"
        type_line = f"# TYPE {metric}"
        assert help_line in text, f"HELP line for {metric} not found"
        assert type_line in text, f"TYPE line for {metric} not found"
    
    # Test histogram-specific elements for both histograms
    histogram_metrics = [
        "vllm_time_to_first_token_seconds",
        "vllm_e2e_request_latency_seconds"
    ]
    
    for metric in histogram_metrics:
        # Check buckets
        assert f"{metric}_bucket" in text, f"Bucket lines for {metric} not found"
        assert f"{metric}_sum" in text, f"Sum line for {metric} not found"
        assert f"{metric}_count" in text, f"Count line for {metric} not found"
        
        # Verify bucket structure
        bucket_lines = [line for line in text.split('\n') if f'{metric}_bucket' in line]
        assert len(bucket_lines) >= 3, f"Insufficient bucket lines for {metric}"
        
        # Verify sum and count lines
        sum_lines = [line for line in text.split('\n') if f'{metric}_sum' in line]
        count_lines = [line for line in text.split('\n') if f'{metric}_count' in line]
        assert len(sum_lines) >= 1, f"Missing sum line for {metric}"
        assert len(count_lines) >= 1, f"Missing count line for {metric}"
    
    # Test that counters are properly formatted
    counter_metrics = ["vllm_request_success_total", "vllm_generation_tokens_total"]
    for metric in counter_metrics:
        counter_lines = [line for line in text.split('\n') if metric in line and not line.startswith('#')]
        assert len(counter_lines) >= 1, f"Missing counter value line for {metric}"
    
    # Test that gauges are properly formatted  
    gauge_metrics = [
        "vllm_num_requests_running",
        "vllm_num_requests_waiting", 
        "vllm_gpu_cache_usage_perc",
        "vllm_gpu_utilization"
    ]
    for metric in gauge_metrics:
        gauge_lines = [line for line in text.split('\n') if metric in line and not line.startswith('#')]
        assert len(gauge_lines) >= 1, f"Missing gauge value line for {metric}"


def test_metrics_endpoint_no_server_required():
    """Test that endpoint works without requiring external server or backend services"""
    import backend.metrics.prometheus_metrics as prom
    
    # Minimal valid Prometheus output
    def fake_generate_metrics():
        return b"# HELP test_metric Test metric\n# TYPE test_metric gauge\ntest_metric 1.0\n"
    
    monkeypatch = pytest.MonkeyPatch()
    monkeypatch.setattr(prom, 'generate_metrics', fake_generate_metrics)

    from backend.main import app
    client = TestClient(app)
    resp = client.get("/api/metrics")
    
    assert resp.status_code == 200
    assert "test_metric" in resp.text
