apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm-lab-dev
resources:
  - vllm-rbac.yaml
  - vllm-runtime.yaml
  - vllm-inferenceservice.yaml
  - 06-vllm-monitoring.yaml
  - vllm-networkpolicy.yaml
