apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-config
  namespace: vllm
data:
  MAX_NUM_SEQS: "256"
  GPU_MEMORY_UTILIZATION: "0.90"
  MAX_MODEL_LEN: "8192"
  MAX_NUM_BATCHED_TOKENS: "2048"
  BLOCK_SIZE: ""
  SWAP_SPACE: ""
  ENABLE_ENFORCE_EAGER: ""
  ENABLE_CHUNKED_PREFILL: ""
