apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llm-ov
  namespace: vllm
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-openvino-runtime
      resources:
        requests:
          cpu: "4"
          memory: "8Gi"
        limits:
          cpu: "8"
          memory: "16Gi"
      volumeMounts:
        - name: models
          mountPath: /models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: model-pvc
