apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vllm-optimizer-backend-role
  namespace: vllm
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
- apiGroups: ["v1"]
  resources: ["configmaps"]
  verbs: ["get", "list", "patch"]
- apiGroups: ["v1"]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: ["v1"]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-optimizer-backend-rb
  namespace: vllm
subjects:
- kind: ServiceAccount
  name: vllm-optimizer-backend
  namespace: vllm-optimizer-dev
roleRef:
  kind: Role
  name: vllm-optimizer-backend-role
  apiGroup: rbac.authorization.k8s.io
