apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llm-ov
  namespace: vllm-lab-dev
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-openvino-runtime
      storageUri: oci://quay.io/joopark/ai1/modelcar-phi-4-mini-instruct-int4-ov
      args:
        - --max-num-seqs=256
        - --gpu-memory-utilization=0.90
        - --max-model-len=8192
        - --max-num-batched-tokens=2048
      resources:
        requests:
          cpu: "4"
          memory: "8Gi"
        limits:
          cpu: "8"
          memory: "16Gi"
