apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm-optimizer-prod
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/name: vllm-optimizer-prod
      app.kubernetes.io/component: production
      app.kubernetes.io/version: "1.0.0"
patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: vllm-optimizer-prod
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: vllm-optimizer-configmap-editor
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: vllm-optimizer-prod
  - target:
      kind: Deployment
      name: vllm-optimizer-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/joopark/vllm-optimizer-backend:1.0.0
  - target:
      kind: Deployment
      name: vllm-optimizer-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/joopark/vllm-optimizer-frontend:1.0.0
      - op: replace
        path: /spec/template/spec/containers/1/resources/requests/cpu
        value: "50m"
      - op: replace
        path: /spec/template/spec/containers/1/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/template/spec/containers/1/resources/limits/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/1/resources/limits/memory
        value: "128Mi"
  - target:
      kind: ConfigMap
      name: vllm-optimizer-config
    patch: |-
      - op: add
        path: /data/VLLM_ENDPOINT
        value: "https://llm-ov-predictor.vllm-lab-prod.svc.cluster.local:8080"
      - op: add
        path: /data/VLLM_NAMESPACE
        value: "vllm-lab-prod"
      - op: add
        path: /data/VLLM_DEPLOYMENT_NAME
        value: "llm-ov"
      - op: add
        path: /data/VLLM_CR_TYPE
        value: "inferenceservice"
  - target:
      kind: PrometheusRule
      name: vllm-optimizer-alerts
    patch: |-
      - op: replace
        path: /spec/groups/2/rules/0/expr
        value: |
          kube_deployment_status_replicas_available{deployment="llm-ov-predictor"}
          <
          kube_deployment_spec_replicas{deployment="llm-ov-predictor"} * 0.5
